name: Deploy to Namecheap Hosting

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy Files via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.HOSTNAME }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          protocol: ftp
          port: 21
          local-dir: ./
          server-dir: /moniemate.site.je/htdocs/

          # Keeps hosting files safe
          dangerous-clean-slate: false

          # Protect uploads and ignore unnecessary files
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            **/.github/**
            **/.env
            **/README.md
            uploads/**
            /uploads/**